version: '3.8'
services:
  backend:
    container_name: backend
    image: bianbbc87/togethering:1.0
    ports:
      - 8080:8080
    restart: "always"
    env_file:
      - .env
    networks:
      - my-network


  nginx:
    container_name: nginx
    image: bianbbc87/togethering-nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - "backend"
    networks:
      - my-network

networks:
  my-network: