version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - '8080:8080'
    environment:
      MYSQL_USER: user
      SPRING_DATASOURCE_URL: ${PROD_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_DRIVER: ${PROD_SPRING_DATASOURCE_DRIVER}
      SPRING_DATASOURCE_USERNAME: ${PROD_SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PROD_SPRING_DATASOURCE_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - ./backend:/app  # 모든 backend 디렉토리를 /app에 마운트