version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: always
    ports:
      - '3000:80'
    depends_on:
      - backend
    networks:
      - network
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
      args:
        ENV_SPRING_DATASOURCE_PASSWORD: ${ENV_SPRING_DATASOURCE_PASSWORD}
        ENV_MYSQL_DATABASE_NAME: ${ENV_MYSQL_DATABASE_NAME}
    ports:
      - '3306:3306'
    volumes:
      - ./db/store:/var/lib/mysql #store는 기본이 ignore이긴 함!
    networks:
      - network
    environment:
      MYSQL_ROOT_PASSWORD: ${ENV_SPRING_DATASOURCE_PASSWORD}
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${ENV_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_DRIVER: ${ENV_SPRING_DATASOURCE_DRIVER}
      SPRING_DATASOURCE_USERNAME: ${ENV_SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${ENV_SPRING_DATASOURCE_PASSWORD}
    networks:
      - network

networks:
  network: