import { PLOGGING_COURSE_LIST_SAMPLE } from 'pages/Plogging/Course/Create/constant'
import { MeetingListType } from 'types/meeting'

export const COMMON_MEETING_LIST_SAMPLE: MeetingListType = [
  {
    id: 34,
    name: '도시 산책',
    maxCount: Math.floor(Math.random() * 10) + 1,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[2],
    category: 'WALK',
    dateTime: '2024-05-18T00:00:00',
  },
  {
    id: 33,
    name: '경쾌한 러닝',
    maxCount: Math.floor(Math.random() * 10) + 1,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[1],
    category: 'RUNNING',
    dateTime: '2024-05-17T00:00:00',
  },
  {
    id: 32,
    name: '장거리 자전거 모임',
    maxCount: Math.floor(Math.random() * 10) + 1,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[3],
    category: 'BICYCLE',
    dateTime: '2024-05-16T00:00:00',
  },
  {
    id: 31,
    name: '공원 산책',
    maxCount: Math.floor(Math.random() * 10) + 1,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[0],
    category: 'WALK',
    dateTime: '2024-05-15T00:00:00',
  },
  {
    id: 30,
    name: '빠른 러닝 팀',
    maxCount: Math.floor(Math.random() * 10) + 1,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[2],
    category: 'RUNNING',
    dateTime: '2024-05-14T00:00:00',
  },
  {
    id: 29,
    name: '산악 자전거 팀',
    maxCount: Math.floor(Math.random() * 10) + 1,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[1],
    category: 'BICYCLE',
    dateTime: '2024-05-13T00:00:00',
  },
  {
    id: 28,
    name: '해변 산책',
    maxCount: Math.floor(Math.random() * 10) + 1,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[3],
    category: 'WALK',
    dateTime: '2024-05-12T00:00:00',
  },
  {
    id: 27,
    name: '주말 러닝',
    maxCount: Math.floor(Math.random() * 10) + 1,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[0],
    category: 'RUNNING',
    dateTime: '2024-05-11T00:00:00',
  },
  {
    id: 26,
    name: '자전거 대회 준비 팀',
    maxCount: Math.floor(Math.random() * 10) + 1,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[2],
    category: 'BICYCLE',
    dateTime: '2024-05-10T00:00:00',
  },
  {
    id: 25,
    name: '밤 산책 모임',
    maxCount: Math.floor(Math.random() * 10) + 1,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[1],
    category: 'WALK',
    dateTime: '2024-05-09T00:00:00',
  },
  {
    id: 24,
    name: '아침 러닝 팀',
    maxCount: Math.floor(Math.random() * 10) + 1,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[3],
    category: 'RUNNING',
    dateTime: '2024-05-08T00:00:00',
  },
  {
    id: 23,
    name: '즐거운 자전거 모임',
    maxCount: Math.floor(Math.random() * 10) + 1,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[0],
    category: 'BICYCLE',
    dateTime: '2024-05-07T00:00:00',
  },
  {
    id: 22,
    name: '힐링 산책 모임',
    maxCount: Math.floor(Math.random() * 10) + 1,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[2],
    category: 'WALK',
    dateTime: '2024-05-06T00:00:00',
  },
  {
    id: 21,
    name: '친구들과 러닝',
    maxCount: Math.floor(Math.random() * 10) + 1,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[1],
    category: 'RUNNING',
    dateTime: '2024-05-05T00:00:00',
  },
  {
    id: 20,
    name: '주말 자전거 여행',
    maxCount: Math.floor(Math.random() * 10) + 1,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[3],
    category: 'BICYCLE',
    dateTime: '2024-05-04T00:00:00',
  },
  {
    id: 19,
    name: '도심 속 산책',
    maxCount: Math.floor(Math.random() * 10) + 1,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[0],
    category: 'WALK',
    dateTime: '2024-05-03T00:00:00',
  },
  {
    id: 18,
    name: '새벽 러닝 모임',
    maxCount: Math.floor(Math.random() * 10) + 1,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[2],
    category: 'RUNNING',
    dateTime: '2024-05-02T00:00:00',
  },
  {
    id: 17,
    name: '자전거 출퇴근 모임',
    maxCount: Math.floor(Math.random() * 10) + 1,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[1],
    category: 'BICYCLE',
    dateTime: '2024-05-01T00:00:00',
  },
  {
    id: 16,
    name: '여유롭게 걸어요!',
    maxCount: Math.floor(Math.random() * 10) + 1,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[3],
    category: 'WALK',
    dateTime: '2024-04-30T00:00:00',
  },
  {
    id: 15,
    name: '산책 모임이 좋아요!',
    maxCount: Math.floor(Math.random() * 10) + 1,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[0],
    category: 'WALK',
    dateTime: '2024-04-29T00:00:00',
  },
  {
    id: 14,
    name: '자전거 함께 타요!',
    maxCount: Math.floor(Math.random() * 10) + 1,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[2],
    category: 'BICYCLE',
    dateTime: '2024-04-28T00:00:00',
  },
  {
    id: 13,
    name: '러닝 즐거움 모임!',
    maxCount: Math.floor(Math.random() * 10) + 1,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[1],
    category: 'RUNNING',
    dateTime: '2024-04-27T00:00:00',
  },
] as MeetingListType

export const PLOGGING_MEETING_LIST_SAMPLE: MeetingListType = [
  {
    id: 7,
    name: '테스트 용도에요!',
    maxCount: 2,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[2],
    category: 'PLOGGING',
    dateTime: '2024-04-29T00:00:00',
  },
  {
    id: 6,
    name: '테스트 용도에요!',
    maxCount: 10,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[3],
    category: 'PLOGGING',
    dateTime: '2024-04-20T00:00:00',
  },
  {
    id: 5,
    name: '테스트 용도에요!',
    maxCount: 6,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[1],
    category: 'PLOGGING',
    dateTime: '2024-04-25T00:00:00',
  },
  {
    id: 4,
    name: '테스트 할거에요 그런 용도에요!',
    maxCount: 2,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[2],
    category: 'PLOGGING',
    dateTime: '2024-08-01T00:00:00',
  },
  {
    id: 3,
    name: '테스트 용도에요2231!',
    maxCount: 5,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[3],
    category: 'PLOGGING',
    dateTime: '2024-07-29T00:00:00',
  },
  {
    id: 2,
    name: '교수님 사랑해요!',
    maxCount: 3,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[0],
    category: 'PLOGGING',
    dateTime: '2024-02-28T00:00:00',
  },
  {
    id: 1,
    name: '교수님 좋아해요!',
    maxCount: 7,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[5],
    category: 'PLOGGING',
    dateTime: '2024-09-27T00:00:00',
  },
  {
    id: 0,
    name: '교사모!',
    maxCount: 2,
    courseItem: PLOGGING_COURSE_LIST_SAMPLE.courseList[1],
    category: 'PLOGGING',
    dateTime: '2024-07-06T00:00:00',
  },
]

export const ALL_MEETING_LIST_SAMPLE = [...COMMON_MEETING_LIST_SAMPLE, ...PLOGGING_MEETING_LIST_SAMPLE]
