server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  devtools:
    restart:
      enabled: true
      additional-paths:
        - "."
    livereload:
      enabled: true
      trigger-file: .restart
    remote:
      secret: mysecret

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
      dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: ${GOOGLE_SCOPE}
            authorization-grant-type: ${GOOGLE_AUTHORIZATION_GRANT_TYPE}
            redirect-uri: ${GOOGLE_REDIRECT_URI}

logging:
  level:
    "[com.example.server]": INFO
    "[org.hibernate.type]": TRACE
jwt:
  secret: ${JWT_SECRET}
greeting:
  message: this is prod application.yml