server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  devtools:
    restart:
      enabled: true
      additional-paths:
        - "."
    livereload:
      enabled: true
      trigger-file: .restart
    remote:
      secret: mysecret
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    path match:
      matching-strategy: ant_path_matcher

logging:
  level:
    "[com.example.server]": INFO
    "[org.hibernate.type]": TRACE
greeting:
  message: this is dev application.yml